server.port=8085

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=hulkaach
spring.rabbitmq.password=new_passwd2

spring.datasource.url=jdbc:postgresql://localhost:5400/filestorage
spring.datasource.username=hulkaach
spring.datasource.password=new_passwd2
spring.jpa.generate-ddl=true

token=7980818479:AAEyKP2smQPbaDYZ7V7O-lZMp_4iVprfOYA
service.file_info.uri=https://api.telegram.org/bot{token}/getFile?file_id={fileId}
service.file_storage.uri=https://api.telegram.org/file/bot{token}/{filePath}

link.address=127.0.0.1:8086
salt=LKHALSNKLhduiqhlkdmslbioqhwio09ujkjwbkj